# Site settings
title: morriswinkler.github.io
person: morris winkler
email: m.winkler@laydrop.com
url: https://morriswinkler.github.io
description: "This is the homepage of Morris Winkler, containing my work and project references."
skills: "System Programmer - Hardware Developer - Roboticist"
meta_author: Winkler Morris

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag) see https://github.com/thomaspark/bootswatch/tree/gh-pages/flatly
color:
  primary: 1695A3 #80B3FF
  primary-rgb: "34, 83, 120" #"24,288,156" #"128,179,255"
  secondary: 225378 #2c3e50 #FD6E8A
  secondary-dark: 1E4769 #233140 #A2122F
  danger: EB7F00

# Footer settings
footer:
  copyright: Morris Winkler
  location: Home
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100010656461890
  - title: stack-overflow
    url: http://stackoverflow.com/users/6501417/morris-winkler
  #- title: bitbucket
  #  url: http://bitbucket.org/
  - title: github
    url: http://github.com/morriswinkler

# Postal address (add as many lines as necessary)
address:
  - line: Rosenthaler Platz
  - line: 10115 Berlin, Germany

# Credits content
credits: 'email: m.winker@laydrop.com <br>phone: +49 (0) 176 396 596 98'

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sass-converter

sass:
    style: compressed
